package org.htmlcleaner.conditional;

import org.htmlcleaner.TagNode;

public class TagNodeAutoGeneratedCondition implements ITagNodeCondition {
    public static final TagNodeAutoGeneratedCondition INSTANCE = new TagNodeAutoGeneratedCondition();

    public String toString() {
        return "auto generated tagNode";
    }

    public boolean satisfy(TagNode tagNode) {
        return tagNode.isAutoGenerated() && tagNode.isEmpty();
    }
}
